info:
  version: 1.0.0
  title: Ordering and Fulfillment
  name: ordering-and-fulfillment
gateways:
  - datapower-api-gateway
plans:
  default-plan:
    title: Default Plan
    description: Default Plan
    rate-limits:
      default:
        value: 100/1hour
    apis:
      order1.0.0: {}
      stock1.0.0: {}
apis:
  order1.0.0:
    $ref: api/orders_api.yaml
  stock1.0.0:
    $ref: api/stock.yaml
visibility:
  view:
    type: public
    orgs: []
    tags: []
    enabled: true
  subscribe:
    type: authenticated
    orgs: []
    tags: []
    enabled: true
product: 1.0.0

